name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
          cli: latest
    - name: Install dependencies
      run: clojure -A:test -P
    - name: Run tests
      run: clojure -T:build ci
